export const MOVIES_LIST = 'MOVIES_LIST';
export const LOAD_MORE_MOVIES = 'LOAD_MORE_MOVIES';
export const CHANGE_MOVIE_TYPE = 'CHANGE_MOVIE_TYPE';
export const START_LOADING_MOVIES = 'START_LOADING_MOVIES';
export const MOVIES_LOADING_FINISHED = 'MOVIES_LOADING_FINISHED';
export const SEARCH_MOVIES_RESULT = 'SEARCH_MOVIES_RESULT';
export const SEARCH_MOVIES_QUERY = 'SEARCH_MOVIES_QUERY';
export const SET_ERROR = 'SET_ERROR';
